### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by samek** [mesosphere/cassandra-mesos-deprecated#141]
Hi, 
We're experiencing GC overhead limit exceeded every couple of days. Scheduler dies and it's not restarted by marathon. 

So: 
Mesos framework log:

```
    2015-09-11 09:53:33,589:6395(0x7f197eff5700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=master.mesos:2181 sessionTimeout=10000 watcher=0x7f19bd4d8860 sessionId=0 sessionPasswd=<null> context=0x7f19440015b0 flags=0
    2015-09-11 09:53:33,591:6395(0x7f1969ddd700):ZOO_INFO@check_events@1703: initiated connection to server [10.0.0.137:2181]
    2015-09-11 09:53:33,594:6395(0x7f1969ddd700):ZOO_INFO@check_events@1750: session establishment complete on server [10.0.0.137:2181], sessionId=0xd84f3f334beb0051, negotiated timeout=10000
    I0911 09:53:33.594823  6480 group.cpp:313] Group process (group(1)@10.0.0.188:57079) connected to ZooKeeper
    I0911 09:53:33.594868  6480 group.cpp:790] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
    I0911 09:53:33.594898  6480 group.cpp:385] Trying to create path '/mesos' in ZooKeeper
    I0911 09:53:33.596679  6483 detector.cpp:138] Detected a new leader: (id='126')
    I0911 09:53:33.596853  6470 group.cpp:659] Trying to get '/mesos/info_0000000126' in ZooKeeper
    I0911 09:53:33.597592  6477 detector.cpp:452] A new leading master (UPID=master@10.0.0.235:5050) is detected
    I0911 09:53:33.597689  6479 sched.cpp:254] New master detected at master@10.0.0.235:5050
    I0911 09:53:33.597853  6479 sched.cpp:264] No credentials provided. Attempting to register without authentication
    I0911 09:53:33.600744  6470 sched.cpp:448] Framework registered with 20150703-081340-2281701386-5050-48159-0000
    2015-09-11 17:18:48,022:6395(0x7f197dff3700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 12ms
    Exception in thread "Thread-162360" java.lang.OutOfMemoryError: GC overhead limit exceeded
            at java.lang.String.substring(Unknown Source)
            at java.lang.String.subSequence(Unknown Source)
            at com.google.protobuf.TextFormat$TextGenerator.print(TextFormat.java:526)
            at com.google.protobuf.TextFormat$Printer.printSingleField(TextFormat.java:334)
            at com.google.protobuf.TextFormat$Printer.printField(TextFormat.java:283)
            at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:273)
            at com.google.protobuf.TextFormat$Printer.access$400(TextFormat.java:248)
            at com.google.protobuf.TextFormat.print(TextFormat.java:71)
            at com.google.protobuf.TextFormat.printToString(TextFormat.java:118)
            at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:106)
            at java.lang.String.valueOf(Unknown Source)
            at java.lang.StringBuilder.append(Unknown Source)
            at java.util.AbstractCollection.toString(Unknown Source)
            at io.mesosphere.mesos.util.ProtoUtils.protoToString(ProtoUtils.java:50)
            at io.mesosphere.mesos.frameworks.cassandra.scheduler.CassandraScheduler.resourceOffers(CassandraScheduler.java:112)
    I0914 05:07:29.821909  6475 sched.cpp:1623] Asked to abort the driver
    I0914 05:07:29.825697  6475 sched.cpp:856] Aborting framework '20150703-081340-2281701386-5050-48159-0000'
    I0914 05:07:30.358397  6396 sched.cpp:1589] Asked to stop the driver
    I0914 05:07:30.361979  6473 sched.cpp:831] Stopping framework '20150703-081340-2281701386-5050-48159-0000'
```

Then In marathon we're getting: (But it never get's scaled to 1) 

```
[2015-09-14 05:07:30,415] INFO Need to scale /cassandra/cluster from 0 up to 1 instances (mesosphere.marathon.SchedulerActions:529)
```

The json for marathon is:  (We only copied cassandra.tar.gz and java to local web server from downloads.mesosphere.io) 

```
    {
      "id": "/cassandra/cluster",
      "instances": 1,
      "cpus": 0.5,
      "mem": 512,
      "ports": [10050],
      "uris": [
        "http://repo.marathon.mesos:9022/cassandra-mesos-0.2.0-1.tar.gz",
        "http://repo.marathon.mesos:9022/jre-7u76-linux-x64.tar.gz"
      ],
      "env": {
        "MESOS_ZK": "zk://master.mesos:2181/mesos",
        "JAVA_OPTS": "-Xms256m -Xmx256m",
        "CASSANDRA_CLUSTER_NAME": "kong-cluster",
        "CASSANDRA_ZK": "zk://master.mesos:2181/cassandra-mesos",
        "CASSANDRA_NODE_COUNT": "3",
        "CASSANDRA_RESOURCE_CPU_CORES": "2.0",
        "CASSANDRA_RESOURCE_MEM_MB": "2048",
        "CASSANDRA_RESOURCE_DISK_MB": "2048",
        "CASSANDRA_HEALTH_CHECK_INTERVAL_SECONDS": "60",
        "CASSANDRA_ZK_TIMEOUT_MS": "10000"
      },
      "cmd": "$(pwd)/jre*/bin/java $JAVA_OPTS -classpath cassandra-mesos-framework.jar io.mesosphere.mesos.frameworks.cassandra.framework.Main",
      "constraints": [
            ["net_video", "CLUSTER", "false"]
      ],
      "healthChecks": [
        {
          "gracePeriodSeconds": 120,
          "intervalSeconds": 30,
          "maxConsecutiveFailures": 0,
          "path": "/health/cluster",
          "portIndex": 0,
          "protocol": "HTTP",
          "timeoutSeconds": 5
        },
        {
          "gracePeriodSeconds": 120,
          "intervalSeconds": 30,
          "maxConsecutiveFailures": 3,
          "path": "/health/process",
          "portIndex": 0,
          "protocol": "HTTP",
          "timeoutSeconds": 5
        }
      ]
    }
```

To get it up and running again we had to manually restart the cassandra framework app in marathon.

Is this a Marathon problem or the framework ? 
thanks.

**Comment by kensipe** [comment]
hey @samek 

It would be great to understand the details of how you got an OOM situation.  Are you dealing with a large cluster env?    Also the logs are incomplete on the mesos log.   It seems something requested the framework to stop.  Was this a shutdown request? or a dcos package uninstall?

regarding the marathon restart failure.  The likely cause of this based on the information provided is this....  If a framework was asked to be shutdown, then a restart of cassandra would not startup based on values in zookeeper.  In order to start cassandra with the same framework name, it is necessary to clear zk.   This appears to be working as expected.

let me know if there is more to follow up on here.

**Comment by samek** [comment]
@kensipe 
My cluster is small in all views, cassandra: 3 nodes, mesos: 20 slaves. 
No human actually did request the shutdown or tried to uninstall it. This just happens after a few days. (repeatable) 

I've added -XX:-UseConcMarkSweepGC to JAVA_OPTS (currently JAVA_OPTS=-Xms256m -Xmx256m -XX:-UseConcMarkSweepGC) in marathon json. Currently it's up for 5 days. 

When it stops again (if it does) I'll try getting more logs out of it.

**Comment by triclambert** [comment]
This repository is deprecated. Please use the latest supported framework here: https://github.com/mesosphere/dcos-cassandra-service, and provide feedback for us here:  https://dcosjira.atlassian.net/browse/CASSANDRA.
